name = "leverageai-website"
compatibility_date = "2024-07-30"
pages_build_output_dir = "out"

[build]
command = "npm run build"

[env.production]
account_id = "a5335954d3ced04c5f63a35b0454c266"

[env.production.vars]
NODE_ENV = "production"